[package]
name = "deku-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
binrw = "0.11.2"
bitvec = "1.0.1"
deku = "0.16.0"
serde = { version = "1.0.174", features = ["derive"] }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "serialize"
harness = false
