[package]
name = "deku-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.11.2"
bitvec = "1.0.1"
deku = { git = "https://github.com/sharksforarms/deku/", branch = "impl-reader" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "serialize"
harness = false
