on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  pages: write
  id-token: write

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: dtolnay/rust-toolchain@be73d7920c329f220ce78e0234b8f96b7ae60248 # master
        with:
          toolchain: stable
      - run: cargo +stable bench
      - run: mkdir -p dist/release
      - run: mv target/criterion/* dist/release/
      - run: cargo +stable bench --profile perf
      - run: mkdir -p dist/perf
      - run: mv target/criterion/* dist/perf/
      - name: Fix permissions
        run: |
          chmod -c -R +rX "dist/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload Pages artifact
        id: github-pages
        uses: actions/upload-artifact@v4
        with:
          name: "github-pages"
          path: "dist"

  # Deploy
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: bench

    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
