on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # master
        with:
          toolchain: 1.87.0
      - run: cargo +1.87.0 bench
      - run: mkdir -p dist/release
      - run: mv target/criterion/* dist/release/
      - run: cargo +1.87.0 bench --profile perf
      - run: mkdir -p dist/perf
      - run: mv target/criterion/* dist/perf/
      - name: Fix permissions
        run: |
          chmod -c -R +rX "dist/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload Pages artifact
        id: github-pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: "github-pages"
          path: "dist"

  deploy:
    needs: bench
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
